// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using homework_2sem_2.DataAccess;

#nullable disable

namespace homework_2sem_2.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("homework_2sem_2.DataAccess.Models.Lottery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DrawTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrizeFund")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("numeric");

                    b.PrimitiveCollection<int[]>("WinningCombination")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("Id");

                    b.ToTable("Lotteries");
                });

            modelBuilder.Entity("homework_2sem_2.DataAccess.Models.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("homework_2sem_2.DataAccess.Models.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsWinning")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LotteryId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<int[]>("Numbers")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LotteryId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("homework_2sem_2.DataAccess.Models.Lottery", b =>
                {
                    b.OwnsOne("homework_2sem_2.DataAccess.Models.NumberRange", "NumberRange", b1 =>
                        {
                            b1.Property<Guid>("LotteryId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Max")
                                .HasColumnType("integer");

                            b1.Property<int>("Min")
                                .HasColumnType("integer");

                            b1.Property<int>("NumbersPerTicket")
                                .HasColumnType("integer");

                            b1.HasKey("LotteryId");

                            b1.ToTable("Lotteries");

                            b1.WithOwner()
                                .HasForeignKey("LotteryId");
                        });

                    b.Navigation("NumberRange");
                });

            modelBuilder.Entity("homework_2sem_2.DataAccess.Models.Participant", b =>
                {
                    b.OwnsOne("homework_2sem_2.DataAccess.Models.ContactInfo", "ContactInfo", b1 =>
                        {
                            b1.Property<Guid>("ParticipantId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ParticipantId");

                            b1.ToTable("Participants");

                            b1.WithOwner()
                                .HasForeignKey("ParticipantId");
                        });

                    b.Navigation("ContactInfo");
                });

            modelBuilder.Entity("homework_2sem_2.DataAccess.Models.Ticket", b =>
                {
                    b.HasOne("homework_2sem_2.DataAccess.Models.Lottery", "Lottery")
                        .WithMany("Tickets")
                        .HasForeignKey("LotteryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("homework_2sem_2.DataAccess.Models.Participant", "Owner")
                        .WithMany("Tickets")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("homework_2sem_2.DataAccess.Models.PurchaseInfo", "PurchaseInfo", b1 =>
                        {
                            b1.Property<Guid>("TicketId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("Date")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("PurchaseNumber")
                                .HasColumnType("uuid");

                            b1.HasKey("TicketId");

                            b1.ToTable("Tickets");

                            b1.WithOwner()
                                .HasForeignKey("TicketId");
                        });

                    b.Navigation("Lottery");

                    b.Navigation("Owner");

                    b.Navigation("PurchaseInfo");
                });

            modelBuilder.Entity("homework_2sem_2.DataAccess.Models.Lottery", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("homework_2sem_2.DataAccess.Models.Participant", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
